# Generated by Django 2.1.5 on 2019-07-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank='true', null='true', upload_to=''),
            preserve_default='true',
        ),
    ]
